### ISSUE TITLE
broken link from SwiftPM details to semver.org

### ISSUE THREAD

**Issue by heckj** [apple/swift-org-website#60]
**Describe the bug**

On the page https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#version, there's a link to `semver.org` that doesn't prefix the `https://`, which results in a broken link that points to `https://docs.swift.org/package-manager/PackageDescription/www.semver.org` instead of `https://www.semver.org`.

**To Reproduce**
1. Go to `https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#version`
2. Click on 'semver.org' link
3. See error (404)

**Expected behavior**
Link navigates to `https://www.semver.org`

**Comment by tomerd** [comment]
cc @amartini51

**Comment by amartini51** [comment]
Thanks @tomerd — checking on which file needs to be edited to fix this.

**Comment by futurejones** [comment]
@amartini51 This issue is not actually in the `swift.org` website. 
It is in the `https://docs.swift.org/package-manager/` site which appears to be generated from the [PackageDescription.md](https://github.com/apple/swift-package-manager/blob/9274d1bf7dcd6ba14340121dc878a647c337ce08/Documentation/PackageDescription.md#version) in the [swift-package-manager](https://github.com/apple/swift-package-manager) repository.

**Comment by tomerd** [comment]
@amartini51 based on what @futurejones is saying this is from https://github.com/apple/swift-package-manager/blob/main/Sources/PackageDescription/Version.swift, but the source file looks correct so maybe an issue in the publishing process / DocC generation?

**Comment by tomerd** [comment]
cc @zkiraly

**Comment by BenedictSt** [comment]
The problem was a broken link in this file: 
https://github.com/apple/swift-package-manager/blob/main/Documentation/PackageDescription.md

`[...](www.semver.org)` instead of `[...](https://semver.org)`

### The issue should be resolved now.

**Comment by 0xTim** [comment]
Thanks!

**Comment by alexandersandberg** [comment]
The issue is still live. When/how can we trigger this to be regenerated?

**Comment by tomerd** [comment]
cc @zkiraly ^^
